import type { Specialist } from "@/lib/content/types";

// Real consultant profiles sourced from London Heart Centre's own published
// team page (londonheartcentre.com/pages/our-team) — names, credentials,
// photos and biography text are taken directly from that source. The
// `conditionsTreated`, `testsPerformed` and `patientConcerns` tags below are
// this project's own mapping of each bio onto our fixed condition/test
// taxonomy (lib/content/conditions.ts, lib/content/tests.ts) — a reasonable
// reading of their published interests, not a verbatim claim — and
// `nhsAppointment`/`availability`/`languages` are inferred from bio text
// where not explicitly stated. All flagged fields should be reviewed by LHC
// before launch; see the [VERIFY] checklist in README.md.
//
// Note: the source team page also lists Dr Siva Sundar, whose bio describes
// a GP/executive-health role (Lead GP for J.P. Morgan's London offices) —
// he is not presented as a cardiology consultant, so has been left out of
// this cardiology-specific specialist directory rather than force-fit.
export const specialists: Specialist[] = [
  {
    slug: "syed-ahsan",
    profileStatus: "verified",
    name: "Dr Syed Ahsan",
    credentials: "BSc MD FRCP",
    mainSpecialty: "Cardiac Electrophysiology & Heart Rhythm",
    bio: "Medical Director of the London Heart Centre.\n\nDr Syed Ahsan is a Consultant Cardiologist and Heart Rhythm Specialist at the Barts Heart Centre. He treats a wide range of heart conditions.\n\nDr Ahsan undertook his cardiology specialist training at various prestigious hospitals in London. These include the Royal Brompton Hospital, Great Ormond Street Hospital and the Heart Hospital where he undertook his fellowship in Cardiac Electrophysiology.\n\nIn his current role Dr Ahsan manages all aspects of adult cardiology. He graduated with a first class honours degree from Guys, King's and St Thomas. His research work was awarded the Royal Society of Medicine National Prize and was presented nationally and internationally at high profile conferences.\n\nHe is a highly experienced operator who routinely implants all types of cardiac pacing and defibrillator devices and performs ablations for arrhythmia using the latest technologies. He also sees and treats patients with blackouts, chest pains and hypertension.\n\nDr Ahsan leads the specialist POTS service at Barts Heart Centre.",
    specialistInterests: [
      "Heart rhythm disorders (arrhythmia)",
      "Pacemaker and defibrillator implantation",
      "POTS (postural orthostatic tachycardia syndrome)",
    ],
    patientConcerns: ["Palpitations", "Blackouts", "Chest pain"],
    nhsAppointment: true,
    conditionsTreated: ["atrial-fibrillation", "hypertension"],
    testsPerformed: ["electrocardiogram", "heart-monitor"],
    training: [
      "Royal Brompton Hospital, Great Ormond Street Hospital and the Heart Hospital — fellowship in Cardiac Electrophysiology",
      "First class honours degree, Guy's, King's and St Thomas'",
    ],
    researchPublications: ["Royal Society of Medicine National Prize-winning research"],
    languages: ["English"],
    availability: { summary: "[VERIFY] Clinic days and times" },
    reviews: [],
    imagePlaceholder: "/media/specialists/placeholder-01.svg",
    photo: "/media/specialists/syed-ahsan.webp",
  },
  {
    slug: "nikolaos-papageorgiou",
    profileStatus: "verified",
    name: "Dr Nikolaos Papageorgiou",
    credentials: "",
    mainSpecialty: "Cardiac Electrophysiology & Heart Failure",
    bio: "Dr Papageorgiou serves as a Consultant Cardiologist & Electrophysiologist at the Lister Hospital in Hertfordshire and at Barts Heart Centre in London.\n\nHaving trained in prestigious centres in Greece, Germany, and United Kingdom, Dr Papageorgiou is highly experienced in all areas of cardiology with a specialist interest in heart rhythm disorders (arrhythmias) and heart failure (pump failure). He also sees patients with palpitations, skipped beats, chest pains, shortness of breath, dizzy spells/blackouts, and high blood pressure.\n\nHe completed his postgraduate degrees at Athens University Medical School in Greece, followed by specialised training in Cardiology and Cardiac Electrophysiology in prestigious centres such as the Heart Hospital/UCLH and the St. Bartholomew's.\n\nHe performs catheter ablation procedures for heart rhythm disorders and implants simple and complex cardiac devices such as pacemakers, defibrillators and resynchronisation devices.\n\nHe holds an Honorary Associate Professorship at the University College London (UCL) and has published over 200 papers.",
    specialistInterests: [
      "Heart rhythm disorders (arrhythmias)",
      "Heart failure",
      "Catheter ablation and cardiac devices",
    ],
    patientConcerns: ["Palpitations", "Breathlessness", "Dizziness or blackouts"],
    nhsAppointment: true,
    conditionsTreated: ["atrial-fibrillation", "heart-failure", "hypertension"],
    testsPerformed: ["electrocardiogram", "heart-monitor"],
    training: [
      "Athens University Medical School, Greece",
      "Cardiology and Cardiac Electrophysiology training — Heart Hospital/UCLH and St Bartholomew's",
    ],
    researchPublications: ["Honorary Associate Professor, UCL — 200+ published papers"],
    languages: ["English"],
    availability: { summary: "[VERIFY] Clinic days and times" },
    reviews: [],
    imagePlaceholder: "/media/specialists/placeholder-02.svg",
    photo: "/media/specialists/nikolaos-papageorgiou.webp",
  },
  {
    slug: "antonis-pavlidis",
    profileStatus: "verified",
    name: "Dr Antonis Pavlidis",
    credentials: "",
    mainSpecialty: "Interventional Cardiology",
    bio: "Dr Antonis Pavlidis is an experienced Consultant Cardiologist based at St Thomas' Hospital, where he specialises in interventional cardiology. He treats a range of conditions, including chest pain, palpitations, valvular heart disease, hypertension, dyslipidaemia, and heart failure. His particular interest is in the treatment of complex coronary disease and the percutaneous treatment of chronic total occlusions.\n\nDr Pavlidis gained his medical degree from the University of Athens before undertaking specialist training at St Thomas' Hospital and the London Chest Hospital. He completed his PhD in primary dyslipidaemia and has authored several book chapters and peer-reviewed publications. He is currently involved in clinical research in the area of preventive and interventional cardiology.",
    specialistInterests: [
      "Complex coronary disease",
      "Chronic total occlusion angioplasty",
      "Preventive cardiology and lipid disorders",
    ],
    patientConcerns: ["Chest pain", "Palpitations", "Breathlessness"],
    nhsAppointment: true,
    conditionsTreated: ["coronary-artery-disease", "valvular-heart-disease", "hypertension"],
    testsPerformed: ["echocardiogram", "exercise-stress-test", "heart-monitor", "blood-pressure-monitoring"],
    training: [
      "Medical degree, University of Athens",
      "Specialist training, St Thomas' Hospital and the London Chest Hospital",
      "PhD in primary dyslipidaemia",
    ],
    researchPublications: ["Book chapters and peer-reviewed publications in preventive and interventional cardiology"],
    languages: ["English"],
    availability: { summary: "[VERIFY] Clinic days and times" },
    reviews: [],
    imagePlaceholder: "/media/specialists/placeholder-03.svg",
    photo: "/media/specialists/antonis-pavlidis.webp",
  },
  {
    slug: "martin-thomas",
    profileStatus: "verified",
    name: "Dr Martin Thomas",
    credentials: "",
    mainSpecialty: "Heart Failure & General Cardiology",
    bio: "Dr Martin Thomas is a Consultant Cardiologist at St Bartholomew's Hospital, London. Trained in all aspects of general cardiology, Dr Thomas has a specialist interest in heart failure management and general cardiology. He is also an expert in aviation cardiology and is a cardiology advisor to the Civil Aviation Authority.\n\nDr Thomas qualified from the University of Southampton, School of Medicine in 1992. He completed his postgraduate specialist training in cardiology at the Sussex Cardiac Centre, Brighton, and St. George's Hospital, London. Additionally, he undertook a one-year senior fellowship in the advanced heart failure and cardiac transplantation service at the Royal Perth Hospital in Western Australia.\n\nDr Thomas was awarded an MD degree from Imperial College, London, after completing his thesis on the clinical problem of heart failure with preserved systolic function. He has since published numerous papers in the field of heart failure.\n\nDr Thomas treats a wide range of conditions including chest pain, breathlessness, palpitations, and high blood pressure.",
    specialistInterests: ["Heart failure management", "General cardiology", "Aviation cardiology"],
    patientConcerns: ["Chest pain", "Breathlessness", "High blood pressure"],
    nhsAppointment: true,
    conditionsTreated: ["heart-failure", "hypertension"],
    testsPerformed: ["electrocardiogram", "echocardiogram"],
    training: [
      "University of Southampton, School of Medicine (1992)",
      "Sussex Cardiac Centre, Brighton and St George's Hospital, London",
      "Senior fellowship, advanced heart failure and cardiac transplantation, Royal Perth Hospital, Australia",
    ],
    researchPublications: [
      "MD, Imperial College London — thesis on heart failure with preserved systolic function",
    ],
    languages: ["English"],
    availability: { summary: "[VERIFY] Clinic days and times" },
    reviews: [],
    imagePlaceholder: "/media/specialists/placeholder-04.svg",
    photo: "/media/specialists/martin-thomas.webp",
  },
  {
    slug: "robin-chung",
    profileStatus: "verified",
    name: "Dr Robin Chung",
    credentials: "",
    mainSpecialty: "General Cardiology & Cardiac Imaging",
    bio: "Dr Robin Chung is a consultant cardiologist who sees patients with breathlessness, palpitations, chest pain, dizziness and valve problems.\n\nHe has broad general cardiology experience and sub-specialty expertise in cardiac imaging, including CT coronary angiography and advanced echocardiography. He has internationally accredited expertise in cardio-oncology, or heart problems before, during, and after treatment in cancer patients.\n\nRobin was trained in echocardiography by the legendary Dr Derek G Gibson at the Royal Brompton Hospital and in advanced echocardiography at Barts Heart Centre. He has an NHS base at the Whittington and honorary consultant at Barts Heart Centre and University College London Hospitals.\n\nDr Chung was involved in the establishment of cardio-oncology services at University College London and Barts Heart Centre.\n\nDr Chung has more than 50 research publications including 30 co-authored journal papers.",
    specialistInterests: ["Advanced echocardiography", "Cardiac CT angiography", "Cardio-oncology"],
    patientConcerns: ["Breathlessness", "Palpitations", "Chest pain"],
    nhsAppointment: true,
    conditionsTreated: ["valvular-heart-disease", "coronary-artery-disease"],
    testsPerformed: ["echocardiogram", "electrocardiogram"],
    training: [
      "Echocardiography training under Dr Derek G Gibson, Royal Brompton Hospital",
      "Advanced echocardiography, Barts Heart Centre",
    ],
    researchPublications: ["50+ research publications, including 30 co-authored journal papers"],
    languages: ["English"],
    availability: { summary: "[VERIFY] Clinic days and times" },
    reviews: [],
    imagePlaceholder: "/media/specialists/placeholder-05.svg",
    photo: "/media/specialists/robin-chung.webp",
  },
  {
    slug: "suneil-aggarwal",
    profileStatus: "verified",
    name: "Dr Suneil Aggarwal",
    credentials: "",
    mainSpecialty: "Structural Intervention & General Cardiology",
    bio: "Dr Suneil Aggarwal is a Cardiologist specialising in valve and congenital heart disease interventions (structural intervention), as well as general cardiology.\n\nHe qualified with multiple distinctions and prizes from University College London in 2002. He completed an MD research degree from University College London. He has been practicing as Lead for Structural Intervention in Liverpool for the last 9 years. He has now relocated to Barts Heart Centre to practice at what is one of the largest cardiac centres in Europe. He has particular expertise in TAVI, mitral interventions, PFO/ASD closure and other complex congenital and valve interventions. His reputation amongst his peers is reflected in twice being elected to the Council of the British Cardiovascular Intervention Society, the national society for Interventional Cardiologists.",
    specialistInterests: [
      "Valve interventions (TAVI, mitral)",
      "Congenital heart disease (PFO/ASD closure)",
      "General cardiology",
    ],
    patientConcerns: ["Breathlessness", "Chest pain"],
    nhsAppointment: true,
    conditionsTreated: ["valvular-heart-disease", "coronary-artery-disease"],
    testsPerformed: ["echocardiogram"],
    training: ["University College London — MD research degree", "Lead for Structural Intervention, Liverpool (9 years)"],
    researchPublications: ["Twice elected to the Council of the British Cardiovascular Intervention Society"],
    languages: ["English"],
    availability: { summary: "[VERIFY] Clinic days and times" },
    reviews: [],
    imagePlaceholder: "/media/specialists/placeholder-06.svg",
    photo: "/media/specialists/suneil-aggarwal.webp",
  },
  {
    slug: "michael-michail",
    profileStatus: "verified",
    name: "Dr Michael Michail",
    credentials: "",
    mainSpecialty: "Interventional Cardiology",
    bio: "Dr Michael Michail is a highly experienced Consultant Interventional Cardiologist with expertise in the diagnosis and treatment of coronary artery disease and structural heart conditions, particularly aortic stenosis. He specialises in advanced interventional procedures, including coronary angioplasty, intravascular imaging, pressure wire studies, and transcatheter aortic valve implantation (TAVI).\n\nDr Michail provides comprehensive cardiac care, managing conditions such as chest pain, breathlessness, palpitations, dizziness, valve disease, hypertension, and high cholesterol.\n\nAfter graduating from St George's Hospital Medical School, London, Dr Michail trained in leading cardiac centres, including The Heart Hospital (UCLH) and Barts Heart Centre. He completed a prestigious three-year funded PhD and interventional fellowship at MonashHeart, Melbourne, in collaboration with University College London.",
    specialistInterests: [
      "Coronary angioplasty and intravascular imaging",
      "TAVI (transcatheter aortic valve implantation)",
      "Structural heart disease",
    ],
    patientConcerns: ["Chest pain", "Breathlessness", "Palpitations"],
    nhsAppointment: true,
    conditionsTreated: ["coronary-artery-disease", "valvular-heart-disease", "hypertension"],
    testsPerformed: ["electrocardiogram", "echocardiogram", "blood-pressure-monitoring"],
    training: [
      "St George's Hospital Medical School, London",
      "The Heart Hospital (UCLH) and Barts Heart Centre",
      "PhD and interventional fellowship, MonashHeart, Melbourne",
    ],
    researchPublications: [],
    languages: ["English"],
    availability: { summary: "[VERIFY] Clinic days and times" },
    reviews: [],
    imagePlaceholder: "/media/specialists/placeholder-07.svg",
    photo: "/media/specialists/michael-michail.webp",
  },
  {
    slug: "konstantinos-savvatis",
    profileStatus: "verified",
    name: "Dr Konstantinos Savvatis",
    credentials: "",
    mainSpecialty: "Inherited Cardiac Conditions & Cardiomyopathy",
    bio: "Konstantinos Savvatis is a Consultant Cardiologist in the Inherited Cardiovascular Diseases Unit at Barts Heart Centre in London and Honorary Associate Professor in University College London and Queen Mary University London. He trained at the Department of Cardiology at the Charité University Hospital in Berlin, Germany, one of the largest centres in Europe focusing on dilated and inflammatory cardiomyopathy.\n\nHis main clinical and academic interests are genetic and inflammatory cardiomyopathies and, especially, the risk assessment and therapy of patients with dilated cardiomyopathy, hypertrophic and arrhythmogenic cardiomyopathy, myocarditis and cardiac involvement in neuromuscular conditions.\n\nHe is specialised in advanced cardiovascular MRI and echocardiography.\n\nHis work has been published in several high impact journals, such as Nature Communications, Circulation, Circulation Research, JACC and European Heart Journal.",
    specialistInterests: [
      "Genetic and inflammatory cardiomyopathies",
      "Cardiovascular MRI and echocardiography",
      "Neuromuscular cardiac conditions",
    ],
    patientConcerns: ["Breathlessness", "Family history"],
    nhsAppointment: true,
    conditionsTreated: ["cardiomyopathy", "heart-failure"],
    testsPerformed: ["echocardiogram"],
    training: ["Charité University Hospital, Berlin — PhD on matrix metalloproteinases in myocarditis"],
    researchPublications: ["Published in Nature Communications, Circulation, Circulation Research, JACC, European Heart Journal"],
    languages: ["English"],
    availability: { summary: "[VERIFY] Clinic days and times" },
    reviews: [],
    imagePlaceholder: "/media/specialists/placeholder-08.svg",
    photo: "/media/specialists/konstantinos-savvatis.webp",
  },
  {
    slug: "john-yap",
    profileStatus: "verified",
    name: "Mr John Yap",
    credentials: "",
    mainSpecialty: "Cardiac Surgery",
    bio: "John Yap is a consultant cardiac surgeon who works in the NHS at St Bartholomew's Hospital, London. He specializes in the surgical treatment of valvular heart disease, mitral repair, Marfan syndrome, valve sparing operations and diseases of the thoracic aorta (including aortic dissection and aneurysms). He has a special interest in surgical and hybrid treatment of atrial fibrillation, including the Maze operation, Convergent procedure and left atrial appendage closure (open and keyhole).\n\nMr Yap completed his medical degree at Glasgow University and went on to specialize in general surgery, obtaining a fellowship with the Royal College of Physicians and Surgeons, Glasgow, in 1992. He further specialized in cardiothoracic surgery at Royal Brompton, London Chest and St Bartholomew's Hospital. He also undertook a research fellowship at Mayo Clinic, USA, where he was awarded a Doctorate degree for his research into gene therapy.",
    specialistInterests: [
      "Valvular heart surgery (mitral repair)",
      "Thoracic aortic surgery",
      "Surgical and hybrid AF treatment (Maze, Convergent)",
    ],
    patientConcerns: ["Breathlessness", "Chest pain"],
    nhsAppointment: true,
    conditionsTreated: ["valvular-heart-disease", "atrial-fibrillation"],
    testsPerformed: [],
    training: [
      "Medical degree, Glasgow University",
      "Fellowship, Royal College of Physicians and Surgeons, Glasgow (1992)",
      "Cardiothoracic surgery — Royal Brompton, London Chest and St Bartholomew's Hospital",
      "Research fellowship, Mayo Clinic, USA — doctorate for gene therapy research",
    ],
    researchPublications: ["Published widely in peer-reviewed journals; presented at national and international meetings"],
    languages: ["English"],
    availability: { summary: "[VERIFY] Clinic days and times" },
    reviews: [],
    imagePlaceholder: "/media/specialists/placeholder-09.svg",
    photo: "/media/specialists/john-yap.webp",
  },
  {
    slug: "sveeta-badiani",
    profileStatus: "verified",
    name: "Dr Sveeta Badiani",
    credentials: "",
    mainSpecialty: "Advanced Echocardiography & Heart Valve Disease",
    bio: "Dr Badiani is a Consultant Cardiologist at Barts Heart Centre and Whipps Cross University Hospital. She graduated from the University of Glasgow and completed her cardiology specialty training in 2021. She specialises in advanced echocardiography (bubble and stress echocardiography, transoesophageal echocardiography), cardiopulmonary exercise testing, heart valve disease and heart failure. She is a vital member of the valve service, leading multidisciplinary team meetings and mentoring physiologists within their clinics.\n\nDr Badiani has completed a PhD in \"Novel Biomarkers in the Assessment of Aortic Stenosis\", has multiple peer reviewed publications and has presented her research at national and international conferences. She has several leadership roles in education and was recently elected to the role of President of the Cardiology Section of the Royal Society of Medicine.\n\nPatients with symptoms of chest pain (angina), shortness of breath, ankle swelling, palpitations, dizziness or fainting will be carefully evaluated, and investigations will be promptly organised to allow accurate diagnosis and treatment. She is also experienced in cardiac risk factor modification, including hypertension and high cholesterol.",
    specialistInterests: [
      "Advanced and stress echocardiography",
      "Heart valve disease",
      "Cardiopulmonary exercise testing",
    ],
    patientConcerns: ["Chest pain", "Breathlessness", "Palpitations"],
    nhsAppointment: true,
    conditionsTreated: ["valvular-heart-disease", "heart-failure", "hypertension"],
    testsPerformed: ["echocardiogram", "cardiopulmonary-exercise-test", "blood-pressure-monitoring"],
    training: ["University of Glasgow", "Cardiology specialty training completed 2021"],
    researchPublications: [
      "PhD: Novel Biomarkers in the Assessment of Aortic Stenosis",
      "President, Cardiology Section, Royal Society of Medicine",
    ],
    languages: ["English"],
    availability: { summary: "[VERIFY] Clinic days and times" },
    reviews: [],
    imagePlaceholder: "/media/specialists/placeholder-10.svg",
    photo: "/media/specialists/sveeta-badiani.webp",
  },
  {
    slug: "ankur-gulati",
    profileStatus: "verified",
    name: "Dr Ankur Gulati",
    credentials: "",
    mainSpecialty: "General Cardiology & Cardiac Imaging",
    bio: "Dr Ankur Gulati is an experienced and highly approachable Consultant Cardiologist offering expert, personalised care at the London Heart Centre. Cambridge-educated with first-class honours, and with further advanced training at Harvard's Brigham and Women's Hospital, he brings world-class expertise to every patient.\n\nHe holds NHS consultant appointments in London at St Thomas' and Queen Elizabeth Hospitals, ensuring his practice remains at the forefront of modern cardiology.\n\nHaving gained dual accreditation in Cardiology and General Internal Medicine, Dr Gulati has the credentials to assess both heart conditions and other health issues that may be related — giving patients clearer answers, streamlined care and confidence that nothing is missed.\n\nHis specialist areas include coronary artery disease, angioplasty and stenting, cardiac imaging (MRI and CT), heart failure and cardiomyopathy, chest pain, palpitations, breathlessness, dizzy spells and blackouts, and cardiac risk factor management (especially high blood pressure and cholesterol). His excellent feedback rating and Doctify Award for Outstanding Patient Experience are testimony to the quality of care he delivers.",
    specialistInterests: [
      "Coronary artery disease and angioplasty",
      "Cardiac imaging (MRI and CT)",
      "Heart failure and cardiomyopathy",
    ],
    patientConcerns: ["Chest pain", "Palpitations", "Breathlessness"],
    nhsAppointment: true,
    conditionsTreated: ["coronary-artery-disease", "heart-failure", "hypertension", "cardiomyopathy"],
    testsPerformed: ["echocardiogram", "electrocardiogram", "blood-pressure-monitoring"],
    training: [
      "Cambridge — first-class honours",
      "Harvard, Brigham and Women's Hospital — advanced training",
      "Dual accreditation in Cardiology and General Internal Medicine",
    ],
    researchPublications: ["Doctify Award for Outstanding Patient Experience"],
    languages: ["English"],
    availability: { summary: "[VERIFY] Clinic days and times" },
    reviews: [],
    imagePlaceholder: "/media/specialists/placeholder-11.svg",
    photo: "/media/specialists/ankur-gulati.webp",
  },
  {
    slug: "kuan-joo-voon",
    profileStatus: "verified",
    name: "Dr Kuan Joo (Victor) Voon",
    credentials: "",
    mainSpecialty: "General Cardiology & Cardiac CT Imaging",
    bio: "Dr Kuan Joo (Victor) Voon works as a Consultant Cardiologist at Homerton Healthcare NHS Foundation Trust and is the cardiac CT lead. He cares for patients in all aspects of adult general cardiology, particularly the non-invasive assessment and management of cardiovascular health. This also includes the diagnosis and treatment of patients with chest pain, breathlessness, palpitations and blackouts. He strongly believes in holistic, personalised care tailored for each individual's needs.\n\nDr Voon graduated in medicine at Trinity College, University of Dublin in 2006 and then went on to complete his specialist training in cardiology in Ireland. As part of this programme, he moved to London to further train in cardiovascular imaging at several prominent tertiary heart centres.\n\nHis subspecialism is in multimodality advanced cardiovascular imaging, particularly in the use of cardiac CT in cardiovascular health. He has been elected as a Fellow of the Royal College of Physicians UK.",
    specialistInterests: [
      "Multimodality cardiovascular imaging",
      "Cardiac CT",
      "General adult cardiology",
    ],
    patientConcerns: ["Chest pain", "Breathlessness", "Palpitations"],
    nhsAppointment: true,
    conditionsTreated: ["coronary-artery-disease"],
    testsPerformed: ["electrocardiogram", "echocardiogram"],
    training: [
      "Trinity College, University of Dublin (2006)",
      "Cardiology specialist training, Ireland",
      "Cardiovascular imaging fellowship, London",
    ],
    researchPublications: [
      "Fellow of the Royal College of Physicians UK",
      "Doctorate in Medicine — novel anti-inflammatory treatment in early cardiovascular disease",
    ],
    languages: ["English"],
    availability: { summary: "[VERIFY] Clinic days and times" },
    reviews: [],
    imagePlaceholder: "/media/specialists/placeholder-12.svg",
    photo: "/media/specialists/kuan-joo-voon.webp",
  },
  {
    slug: "anantharaman-ramasamy",
    profileStatus: "verified",
    name: "Dr Anantharaman Ramasamy",
    credentials: "",
    mainSpecialty: "Interventional Cardiology",
    bio: "Dr Ramasamy is a leading Consultant Cardiologist and Interventional Cardiologist at the internationally recognised Barts Heart Centre, St Bartholomew's Hospital. He also practises at Homerton University Hospital, delivering comprehensive, high-quality care across all aspects of adult cardiology.\n\nHolding dual accreditation in Cardiology and General Internal Medicine, Dr Ramasamy offers a uniquely comprehensive and holistic approach to patient care.\n\nA graduate of the University of Edinburgh with distinction, he completed postgraduate training in Oxford and London before specialist cardiology training at Barts Heart Centre, followed by advanced post-CCT fellowship training in complex coronary intervention and cardiogenic shock at the Royal Brompton Hospital.\n\nDr Ramasamy's PhD from Queen Mary University of London — awarded with no corrections — focused on the most advanced invasive and non-invasive coronary imaging technologies, including NIRS-IVUS, cardiac CT, and multimodality AI-driven plaque assessment.\n\nDr Ramasamy provides expert assessment and treatment for a wide range of conditions, including chest pain, breathlessness, palpitations, blackouts, hypertension, lipid disorders, heart failure, cardiovascular risk assessment, perioperative evaluation, and general cardiac health screening.",
    specialistInterests: [
      "Complex coronary intervention",
      "Intravascular imaging-guided PCI",
      "Cardiac CT and AI-driven imaging",
    ],
    patientConcerns: ["Chest pain", "Breathlessness", "Dizziness or blackouts"],
    nhsAppointment: true,
    conditionsTreated: ["coronary-artery-disease", "heart-failure", "hypertension"],
    testsPerformed: ["echocardiogram", "heart-monitor", "blood-pressure-monitoring", "heart-screening"],
    training: [
      "University of Edinburgh — degree with distinction",
      "Barts Heart Centre — specialist cardiology training",
      "Post-CCT fellowship, complex coronary intervention, Royal Brompton Hospital",
    ],
    researchPublications: [
      "PhD, Queen Mary University of London, awarded with no corrections",
      "Royal Society of Medicine Prize; Best Clinical Case, EuroPCR",
    ],
    languages: ["English"],
    availability: { summary: "[VERIFY] Clinic days and times" },
    reviews: [],
    imagePlaceholder: "/media/specialists/placeholder-13.svg",
    photo: "/media/specialists/anantharaman-ramasamy.webp",
  },
  {
    slug: "filip-zemrak",
    profileStatus: "verified",
    name: "Dr Filip Zemrak",
    credentials: "",
    mainSpecialty: "Heart Failure & Cardiac Devices",
    bio: "Dr Filip Zemrak is a Consultant Cardiologist at St Bartholomew's Hospital (Barts Heart Centre), London, and an Honorary Associate Professor at University College London (UCL).\n\nHe provides expert diagnosis and treatment for a wide range of heart conditions, with particular focus on heart failure (including complex heart failure and optimisation of long-term treatment), adult congenital heart disease, heart rhythm problems including palpitations and atrial fibrillation, advanced cardiac devices (complex ICD therapy, CRT, S-ICD and leadless pacemakers), and cardiovascular prevention and risk assessment.\n\nDr Zemrak graduated in Medicine in 2006 from the Medical University of Łódź (Poland) and completed his specialist medical training in the UK, before being appointed Consultant Cardiologist in 2020. He was awarded a PhD in Cardiovascular Sciences (University of London) in 2017, with research focused on cardiomyopathy, including experience at the National Institutes of Health (NIH) in the United States.\n\nHe leads the CardioMEMS programme at Barts, supporting selected heart failure patients with remote monitoring.",
    specialistInterests: [
      "Heart failure (including CardioMEMS remote monitoring)",
      "Adult congenital heart disease",
      "Cardiac devices (ICD, CRT, S-ICD, leadless pacemakers)",
    ],
    patientConcerns: ["Palpitations", "Breathlessness", "High blood pressure"],
    nhsAppointment: true,
    conditionsTreated: ["heart-failure", "atrial-fibrillation", "hypertension"],
    testsPerformed: ["electrocardiogram", "heart-monitor", "blood-pressure-monitoring"],
    training: [
      "Medical University of Łódź, Poland (2006)",
      "Cardiology training, North-East London",
      "PhD in Cardiovascular Sciences, University of London (2017)",
    ],
    researchPublications: [
      "Research experience at the National Institutes of Health (NIH), USA",
      "Darzi Fellow — heart failure service improvement, East London",
    ],
    languages: ["English"],
    availability: { summary: "[VERIFY] Clinic days and times" },
    reviews: [],
    imagePlaceholder: "/media/specialists/placeholder-14.svg",
    photo: "/media/specialists/filip-zemrak.webp",
  },
  {
    slug: "emmanuel-androulakis",
    profileStatus: "verified",
    name: "Dr Emmanuel Androulakis",
    credentials: "",
    mainSpecialty: "Cardiomyopathy, Sports & Preventive Cardiology",
    bio: "Dr Emmanuel Androulakis is an internationally recognised Consultant Cardiologist and an Academic in renowned UK and international postgraduate programmes. He is a specialist in genetic (familial) heart muscle conditions (cardiomyopathy), sports cardiology, preventive cardiology and multimodality cardiovascular imaging. He strives to apply non-invasive advanced heart diagnostic imaging procedures such as heart MRI, heart CT, advanced echocardiography and stress testing.\n\nFollowing his PhD in cardiovascular genetics and two MSc degrees (Sports Cardiology, St George's University, and Health Economics & Management), his extensive expertise has been honed through years of training in the largest London centres (Royal Brompton & Harefield Hospitals, St George's Hospital/University, St Bartholomew's Hospital), including fellowships in inherited cardiac conditions and cardiomyopathy.\n\nHe is a Consultant Cardiologist at King's College Hospital, London, and has worked for several years with the charity Cardiac Risk in the Young (CRY), screening more than 30,000 young individuals and athletes per year for heart disease. He is credited with more than 120 peer-reviewed medical publications.",
    specialistInterests: [
      "Genetic (familial) cardiomyopathy",
      "Sports cardiology",
      "Multimodality cardiovascular imaging (MRI, CT, echo)",
    ],
    patientConcerns: ["Family history", "Breathlessness"],
    nhsAppointment: true,
    conditionsTreated: ["cardiomyopathy"],
    testsPerformed: ["echocardiogram", "exercise-stress-test", "heart-screening"],
    training: [
      "PhD in cardiovascular genetics",
      "MSc, Sports Cardiology, St George's University",
      "MSc, Health Economics & Management",
    ],
    researchPublications: [
      "120+ peer-reviewed publications",
      "Board member, European Association of Cardiovascular Imaging (EACVI)",
    ],
    languages: ["English"],
    availability: { summary: "[VERIFY] Clinic days and times" },
    reviews: [],
    imagePlaceholder: "/media/specialists/placeholder-15.svg",
    photo: "/media/specialists/emmanuel-androulakis.webp",
  },
  {
    slug: "rui-providencia",
    profileStatus: "verified",
    name: "Professor Rui Providencia",
    credentials: "",
    mainSpecialty: "Cardiac Electrophysiology",
    bio: "Professor Rui Providencia is an Attending Cardiologist and Clinical Academic specializing in cardiac electrophysiology. Following his residency in Portugal (2005–2011), he completed advanced fellowships at Hospital Santa Cruz (Lisbon), Clinique Pasteur (Toulouse, 2012–2014), and The Heart Hospital / St Bartholomew's Hospital (London, 2015–2017). His clinical practice encompasses the full spectrum of cardiovascular disease, with a specific focus on complex interventional arrhythmia procedures — device implantations (pacemakers, ICDs, CRT) and catheter ablations for SVT, atrial fibrillation and ventricular ectopy.\n\nDuring his tenure at University College London (UCL), he secured over £7 million in peer-reviewed funding from the WHO, NIHR, British Heart Foundation, Barts Charity and Biosense Webster. His academic output includes 357 peer-reviewed papers with 19,738 citations (h-index 54). He served for four years as a Commissioner for the Commission on Human Medicines within the UK's MHRA, and serves on the editorial boards of the Cochrane Collaboration, JACC: Advances, Frontiers in Cardiovascular Medicine, and Revista Portuguesa de Cardiologia.",
    specialistInterests: [
      "Complex arrhythmia procedures",
      "Device implantation (pacemakers, ICD, CRT)",
      "Catheter ablation (AF, SVT)",
    ],
    patientConcerns: ["Palpitations", "Breathlessness"],
    nhsAppointment: true,
    conditionsTreated: ["atrial-fibrillation"],
    testsPerformed: ["electrocardiogram", "heart-monitor"],
    training: [
      "Residency, Portugal (2005–2011)",
      "Fellowships — Hospital Santa Cruz (Lisbon); Clinique Pasteur (Toulouse); The Heart Hospital/St Bartholomew's, London",
    ],
    researchPublications: [
      "357 peer-reviewed papers, 19,738 citations (h-index 54)",
      "£7M+ in peer-reviewed research funding (WHO, NIHR, BHF)",
    ],
    languages: ["English"],
    availability: { summary: "[VERIFY] Clinic days and times" },
    reviews: [],
    imagePlaceholder: "/media/specialists/placeholder-16.svg",
    photo: "/media/specialists/rui-providencia.webp",
  },
  {
    slug: "antonio-creta",
    profileStatus: "verified",
    name: "Dr Antonio Creta",
    credentials: "",
    mainSpecialty: "Cardiac Electrophysiology",
    bio: "Dr Antonio Creta is a Consultant Cardiologist at the Barts Heart Centre, one of Europe's leading cardiac hospitals, and at University College London Hospitals (UCLH). He is Clinical Governance Lead for Cardiac Electrophysiology and leads the Ventricular Tachycardia (VT) programme at Barts, specialising in complex heart rhythm disorders.\n\nHe provides comprehensive general cardiology assessments and specialises in the diagnosis and treatment of arrhythmias, including atrial fibrillation, supraventricular tachycardia (SVT) and ectopic beats. He performs a high volume of procedures, including catheter ablation, atrial fibrillation ablation, pacemaker and ICD implantation, using advanced techniques such as pulsed-field ablation, 3D cardiac mapping and leadless pacemakers.\n\nDr Creta is actively involved in cardiovascular research and has published widely in peer-reviewed journals. He holds a research doctorate focused on atrial fibrillation and a Master's degree in Health Economics from the London School of Economics.",
    specialistInterests: [
      "Complex heart rhythm disorders (VT programme lead)",
      "Atrial fibrillation ablation",
      "Pulsed-field ablation and 3D cardiac mapping",
    ],
    patientConcerns: ["Palpitations", "Chest pain"],
    nhsAppointment: true,
    conditionsTreated: ["atrial-fibrillation"],
    testsPerformed: ["electrocardiogram", "heart-monitor"],
    training: [
      "Research doctorate — atrial fibrillation",
      "Master's in Health Economics, London School of Economics",
    ],
    researchPublications: ["Widely published in peer-reviewed journals"],
    languages: ["English"],
    availability: { summary: "[VERIFY] Clinic days and times" },
    reviews: [],
    imagePlaceholder: "/media/specialists/placeholder-17.svg",
    photo: "/media/specialists/antonio-creta.webp",
  },
  {
    slug: "edward-rowland",
    profileStatus: "verified",
    name: "Dr Edward Rowland",
    credentials: "MD FRCP FESC FACC OBE",
    mainSpecialty: "Heart Rhythm Disorders",
    bio: "Dr Rowland was appointed to the National Heart and Lung Institute and the Royal Brompton National Heart Hospital. He then moved to St George's Hospital, helping to develop the treatment of heart rhythm problems. He was the former medical director of Barts Heart Centre since its formation.",
    specialistInterests: ["Heart rhythm disorder treatment"],
    patientConcerns: ["Palpitations"],
    nhsAppointment: true,
    conditionsTreated: ["atrial-fibrillation"],
    testsPerformed: [],
    training: [
      "National Heart and Lung Institute",
      "Royal Brompton National Heart Hospital",
      "St George's Hospital",
    ],
    researchPublications: [],
    languages: ["English"],
    availability: { summary: "[VERIFY] Clinic days and times" },
    reviews: [],
    imagePlaceholder: "/media/specialists/placeholder-18.svg",
    photo: "/media/specialists/edward-rowland.webp",
  },
];

export function getSpecialistBySlug(slug: string): Specialist | undefined {
  return specialists.find((s) => s.slug === slug);
}
