import type { Specialist } from "@/lib/content/types";

// IMPORTANT: every profile below is placeholder ("sample") content used to
// demonstrate the specialist card and profile templates. Names, credentials,
// training, publications and availability are illustrative only and must be
// replaced with real, consultant-approved data before launch. Do not present
// this data as factual on a live site.
export const specialists: Specialist[] = [
  {
    slug: "naomi-ellery",
    profileStatus: "sample",
    name: "Dr Naomi Ellery [VERIFY]",
    credentials: "MD, FRCP [VERIFY]",
    mainSpecialty: "Interventional Cardiology",
    specialistInterests: [
      "Coronary artery disease",
      "Angina assessment",
      "Coronary imaging",
    ],
    patientConcerns: ["Chest pain", "Breathlessness on exertion", "Angina"],
    nhsAppointment: true,
    conditionsTreated: ["coronary-artery-disease", "atrial-fibrillation"],
    testsPerformed: ["electrocardiogram", "echocardiogram", "exercise-stress-test"],
    training: ["[VERIFY] Medical degree and cardiology training details"],
    researchPublications: ["[VERIFY] Peer-reviewed publications"],
    languages: ["English"],
    availability: { summary: "[VERIFY] Clinic days and times" },
    reviews: [],
    imagePlaceholder: "/media/specialists/placeholder-01.svg",
  },
  {
    slug: "rajan-kapoor",
    profileStatus: "sample",
    name: "Dr Rajan Kapoor [VERIFY]",
    credentials: "MD, FRCP [VERIFY]",
    mainSpecialty: "Cardiac Electrophysiology",
    specialistInterests: [
      "Heart rhythm disorders",
      "Atrial fibrillation",
      "Ambulatory monitoring",
    ],
    patientConcerns: ["Palpitations", "Irregular heartbeat", "Dizziness"],
    nhsAppointment: true,
    conditionsTreated: ["atrial-fibrillation", "cardiomyopathy"],
    testsPerformed: ["electrocardiogram", "heart-monitor"],
    training: ["[VERIFY] Medical degree and electrophysiology training details"],
    researchPublications: ["[VERIFY] Peer-reviewed publications"],
    languages: ["English", "Hindi"],
    availability: { summary: "[VERIFY] Clinic days and times" },
    reviews: [],
    imagePlaceholder: "/media/specialists/placeholder-02.svg",
  },
  {
    slug: "helena-voss",
    profileStatus: "sample",
    name: "Dr Helena Voss [VERIFY]",
    credentials: "MD, FESC [VERIFY]",
    mainSpecialty: "Heart Failure & Cardiomyopathy",
    specialistInterests: [
      "Heart failure management",
      "Cardiomyopathy",
      "Valve disease",
    ],
    patientConcerns: ["Breathlessness", "Fatigue", "Ankle swelling"],
    nhsAppointment: true,
    conditionsTreated: ["heart-failure", "cardiomyopathy", "valvular-heart-disease"],
    testsPerformed: ["echocardiogram", "cardiopulmonary-exercise-test"],
    training: ["[VERIFY] Medical degree and subspecialty training details"],
    researchPublications: ["[VERIFY] Peer-reviewed publications"],
    languages: ["English", "German"],
    availability: { summary: "[VERIFY] Clinic days and times" },
    reviews: [],
    imagePlaceholder: "/media/specialists/placeholder-03.svg",
  },
  {
    slug: "marcus-whitfield",
    profileStatus: "sample",
    name: "Dr Marcus Whitfield [VERIFY]",
    credentials: "MD, FRCP [VERIFY]",
    mainSpecialty: "Hypertension & Preventive Cardiology",
    specialistInterests: [
      "Hypertension management",
      "Cardiovascular risk assessment",
      "Preventive cardiology",
    ],
    patientConcerns: [
      "High blood pressure",
      "Family history of heart disease",
      "General risk assessment",
    ],
    nhsAppointment: false,
    conditionsTreated: ["hypertension"],
    testsPerformed: ["blood-pressure-monitoring", "heart-screening"],
    training: ["[VERIFY] Medical degree and training details"],
    researchPublications: ["[VERIFY] Peer-reviewed publications"],
    languages: ["English"],
    availability: { summary: "[VERIFY] Clinic days and times" },
    reviews: [],
    imagePlaceholder: "/media/specialists/placeholder-04.svg",
  },
  {
    slug: "sarah-okonkwo",
    profileStatus: "sample",
    name: "Dr Sarah Okonkwo [VERIFY]",
    credentials: "MD, FRCP [VERIFY]",
    mainSpecialty: "General Cardiology & Imaging",
    specialistInterests: [
      "Cardiac imaging",
      "Valve disease",
      "Unexplained dizziness",
    ],
    patientConcerns: ["Dizziness or blackouts", "Heart murmur", "General cardiology review"],
    nhsAppointment: true,
    conditionsTreated: ["valvular-heart-disease", "atrial-fibrillation"],
    testsPerformed: ["electrocardiogram", "echocardiogram"],
    training: ["[VERIFY] Medical degree and training details"],
    researchPublications: ["[VERIFY] Peer-reviewed publications"],
    languages: ["English", "Yoruba"],
    availability: { summary: "[VERIFY] Clinic days and times" },
    reviews: [],
    imagePlaceholder: "/media/specialists/placeholder-05.svg",
  },
  {
    slug: "julian-ferris",
    profileStatus: "sample",
    name: "Dr Julian Ferris [VERIFY]",
    credentials: "MD, FACC [VERIFY]",
    mainSpecialty: "Sports & Exercise Cardiology",
    specialistInterests: [
      "Heart screening",
      "Exercise physiology",
      "Family history assessment",
    ],
    patientConcerns: [
      "Heart screening request",
      "Family history of heart disease",
      "Fitness for exercise",
    ],
    nhsAppointment: false,
    conditionsTreated: ["coronary-artery-disease", "cardiomyopathy"],
    testsPerformed: [
      "exercise-stress-test",
      "cardiopulmonary-exercise-test",
      "heart-screening",
    ],
    training: ["[VERIFY] Medical degree and training details"],
    researchPublications: ["[VERIFY] Peer-reviewed publications"],
    languages: ["English", "French"],
    availability: { summary: "[VERIFY] Clinic days and times" },
    reviews: [],
    imagePlaceholder: "/media/specialists/placeholder-06.svg",
  },
];

export function getSpecialistBySlug(slug: string): Specialist | undefined {
  return specialists.find((s) => s.slug === slug);
}
